scss_files: "source/scss/**/*.scss"

linters:
  BangFormat:
    enabled: true

  # .block__element__element has depth of two
  BemDepth:
    enabled: true
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  # This could be potentially problematic for cross-browser support
  DuplicateProperty:
    enabled: true

  # Keeping this in line (heh heh) with JSCS
  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: false # UGLY

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  # Keep things consistent?
  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  ImportantRule:
    enabled: true

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: tab
    width: 1

  LeadingZero:
    enabled: true
    style: include_zero

  # YES!  Cut down the redundancy!!!!
  MergeableSelector:
    enabled: true
    force_nesting: true

  # Maybe revisit this if we decide on BEM or another nomenclature
  NameFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  # NOTE: This is NOT depth of applicability -- that's SelectorDepth!
  # This is simply the depth of rules
  NestingDepth:
    enabled: true
    max_depth: 5
    ignore_parent_selectors: false

  # YES!  No more extending straight rules
  PlaceholderInExtend:
    enabled: true

  PropertyCount:
    enabled: false
    #include_nested: false
    #max_properties: 10

  # @TODO: Revisit this when we all talk about thangs
  PropertySortOrder:
    enabled: false
    #ignore_unspecified: false
    #min_properties: 2
    #separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: [] # We can add experimental properties here!

  # @TODO: Revisit this to ensure proper spacings/rhythms?
  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q',
      'vh', 'vw', 'vmin', 'vmax',
      'deg', 'grad', 'rad', 'turn',
      'ms', 's',
      'Hz', 'kHz',
      'dpi', 'dpcm', 'dppx',
      '%']
    properties: {}

  # To avoid overqualifying selectors (prefer `.sidebar` over `div.sidebar`)
  # @TODO: Tighten/relax the following allowances
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  # This is depth of applicability (https://smacss.com/book/applicability)
  SelectorDepth:
    enabled: true
    max_depth: 5

  SelectorFormat:
    enabled: true
    convention: '^(([a-z]*[-]?[a-z0-9\-]*)([a-z0-9\-]*)?(__[a-z0-9]*[-]?[a-z0-9\-]*)?(--[a-z0-9]*[-]?[a-z0-9\-]*)?)$|(f_[a-zA-Z0-9\-_]*_on)$'

  Shorthand:
    enabled: true
    #allowed_shorthands: [1, 2, 3]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false
    style: space

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  # @TODO: Revisit this!  It could help to ensure consistency
  VariableForProperty:
    enabled: false
    #properties:
      #- color
      #- font

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  # I'm not sure how much Compass support there is,
  # but we should revisit this once we start using Compass 4realz/more heavily
  Compass::*:
    enabled: false
